remote_theme: pages-themes/cayman@v0.2.0
title: Carrie Tian
author: Carrie Tian
email: hi@carrietian.com

# social links
twitter_username: carrietian

show_excerpts: true # set to false to remove excerpts on the homepage
